version: '3'
services: 
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - some-network
    ports:
      - 3000:80
    depends_on: 
      - some-postgres
  some-postgres:
    image: postgres
    networks:
      - some-network
    volumes:
      - ./database:/var/lib/some-postgres/data
    ports: 
      - 5000:5432
    environment: 
      POSTGRES_PASSWORD: mysecretpassword