version: '3'
services: 
  some-postgres:
    image: postgres
    volumes:
      - ./database:/var/lib/some-postgres/data
    ports: 
      - 5000:5432
    environment: 
      POSTGRES_PASSWORD: mysecretpassword